#pragma once

// Copy this file to include/secrets.h and fill in real values locally.
#define SECRET_OPENAI_API_KEY "REPLACE_WITH_OPENAI_API_KEY"
#define SECRET_TELEGRAM_BOT_TOKEN "REPLACE_WITH_TELEGRAM_BOT_TOKEN"
#define SECRET_TELEGRAM_CHAT_ID "REPLACE_WITH_TELEGRAM_CHAT_ID"
#define SECRET_EMQX_APP_SECRET "REPLACE_WITH_EMQX_APP_SECRET"
#define SECRET_MQTT_PASSWORD "REPLACE_WITH_MQTT_PASSWORD"
#define SECRET_EMQX_API "REPLACE_WITH_EMQX_API"
#define SECRET_FCM_API_URL "REPLACE_WITH_FCM_HTTP_V1_URL"
#define SECRET_FCM_DEVICE_TOKEN "REPLACE_WITH_FCM_DEVICE_TOKEN"

